### ISSUE TITLE
[질문] Header에 등록한 token 가져오는 방법

### ISSUE THREAD

**Issue by 2-seo** [codingspecialist/Springboot-Oauth2.0-Facebook-Google-Login-JWT#1]
https://github.com/codingspecialist/Springboot-Oauth2.0-Facebook-Google-Login-JWT/blob/b76c582605a423679dbf238e117a80ab5596fc1e/src/main/java/com/example/springsocial/config/SecurityConfig.java#L94
@codingspecialist 
안녕하세요.
코드 잘 보고 있습니다!

헤더에 등록한 토큰을 웹에서 어떻게 가져올 수 있을지 여쭈어보고 싶어서 이슈 등록하게 되었습니다.

답변해주시면 감사하겠습니다.
감사합니다.

**Comment by codingspecialist** [comment]
브라우저가 그냥 가지고 있다가 다시요청할때 달고 다녀요. 신경안써도.되요 ㅎ 프로토콜이거든요.  앱에서는 직접관리해야되요
​
-----Original Message-----
From: "SeoHyun ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>; ***@***.***>;
Sent: 2021-04-28 (수) 16:06:19 (GMT+09:00)
Subject: [codingspecialist/Springboot-Oauth2.0-Facebook-Google-Login-JWT] [질문] Header에 등록한 token 가져오는 방법 (#1)

https://github.com/codingspecialist/Springboot-Oauth2.0-Facebook-Google-Login-JWT/blob/b76c582605a423679dbf238e117a80ab5596fc1e/src/main/java/com/example/springsocial/config/SecurityConfig.java#L94
@codingspecialist
안녕하세요.
코드 잘 보고 있습니다!
헤더에 등록한 토큰을 웹에서 어떻게 가져올 수 있을지 여쭈어보고 싶어서 이슈 등록하게 되었습니다.
답변해주시면 감사하겠습니다.
감사합니다.

**Comment by 2-seo** [comment]
안녕하세요. 답변 정말 감사합니다!!

그러면 `localStorage` 에 저장하지 않아도 되는 건가요?
저는 지금까지는 response에서 같이 날아온 header의 Authorization을 `localStorage` 에 저장해서
다른 요청 시마다 `getItem()`으로 꺼내서 header에 같이 첨부해서 요청했습니다.

`addHeader()`를 하면 브라우저에서 계속 달고다니면서 요청마다 같이 전송해주는 거로 답변 이해했습니다.
따라서 제가 이해한 대로 로그인 후 `axios`로 Authorization 토큰이 필요한 부분에
header를 빼고 전송해봤는데 토큰은 전송이 안 되서 인증이 안 되더라구요..!ㅜㅜ
제가 어떤 부분에서 틀렸을까요..?!

ps..저희가 모바일 개발도 하고 있는데 모바일 부분도 힌트 주실 수 있으실까요..?

읽어주셔서 감사합니다.

**Comment by codingspecialist** [comment]
jwt토큰을 헤더에 담아서.응답하면 react에서는 로컬스토리지에 담아야하고
클라이언트 쪽 웹브라우저로.전송되요.
당연히.담아야해요.
브라우저가 신경쓸필요가 없다는거지 리엑트도 노드서버위에서 돌기 때문에 거기선 저장해줘야해요

앱은 응답을 다이렉트로.받기 때문에 헤더읽어서 sqllite나 preference에 담아서 관리하면 되요
​
-----Original Message-----

**Comment by 2-seo** [comment]
답변 감사합니다 ^^
